### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by nicholas-gs** [nicholas-gs/dt-duckiebot-interface-cps#3]
**Packages**
- [x] duckiebot_interface
- [x] adafruit_drivers
- [x] button_driver
- [x] camera_driver
- [x] display_driver
- [ ] ~~display_renderers~~
- [ ] #4
- [x] led_emitter
- [ ] ~~robot_http_api~~
- [x] tof_driver
- [x] imu_driver
- [ ] traffic_light
- [x] wheel_encoder
- [x] wheels_driver

**Issues**
- [x] #1 
- [x] #2 

**Things to do**

- [x] How to generate calibration file for `camera_driver`
- [ ] How to generate calibration file for `wheel_encoder`
- [ ] Use `dt_calibration_utils` for reading in calibration file for [`wheel_encoder`](https://github.com/nicholas-gs/dt-duckiebot-interface-cps/blob/7d2b8c5e932997e0f1d55eeaee52067267080b21/wheel_encoder/wheel_encoder/wheel_encoder_node.py#L120-L143)
- [ ] How to generate calibration file for `imu_driver`
- [ ] Test/view image generated by `camera_driver`
